### ISSUE TITLE
Execution aborts after '/rest/servers/husc-pro-mob_2/status' invocation

### ISSUE THREAD

**Issue by alberto-morales** [alberto-morales/commanderJS#1]
Console output:

-------------------------------------------------------------------------------------
Time:  1481584589144
/rest/servers/husc-pro-mob_2/status
getServerStatus
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 172.16.1.146:8081
    at Object.exports._errnoException (util.js:911:11)
    at exports._exceptionWithHostPort (util.js:934:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1076:14)
-------------------------------------------------------------------------------------

URL: http://192.168.1.138:3001/rest/servers/husc-pro-mob_2/status

**Comment by alberto-morales** [comment]
Resolved.
